### ISSUE TITLE
Doesn't work in Win11

### ISSUE THREAD

**Issue by Neikon** [AlfarexGuy2019/GentleFox#1]
![imagen](https://user-images.githubusercontent.com/1765319/136111621-76658b44-6286-45d7-a448-cb876a58fa24.png)

Tab bar disappear, and you can't resize windows to full screen.

Edición	Windows 11 Pro
Versión	21H2
Instalado el	‎05/‎10/‎2021
Versión del sistema operativo	22000.194
Experiencia	Paquete de experiencia de características de Windows 1000.22000.194.0

**Comment by AlfarexGuy2019** [comment]
Hi Neikon, 
I'm still working on the theme. And I've been working on managing to replicate the vibrancy from macOS on Windows using mica. For now, I'm quickly releasing a Windows version of this theme. Thanks for your issue!

**Comment by Razor421** [comment]
how to install in win10

**Comment by AlfarexGuy2019** [comment]
@Neikon @Razor421 I've added the Windows version of the theme.

**Comment by Razor421** [comment]
still not too sure on the installation process.
im on windows 10
