### ISSUE TITLE
Question about UI icons

### ISSUE THREAD

**Issue by NineXYZ** [AlfarexGuy2019/GentleFox#2]
Is it possible to change the default Firefox icons to something more macOS-like? 
Thanks for working in this awesome css!

**Comment by AlfarexGuy2019** [comment]
Hi there @NineXYZ!
Thanks for the compliment. Could you elaborate on the icon topic?

**Comment by NineXYZ** [comment]
I don't have experience doing that and right now I'm busy with my studies, so I can't sorry... Also, apologies for the late response!
